#!/bin/bash

source conf/manager.conf

main_menu () {
    clear
    printf "╭────────────────────────────╮                               ╭─────────╮\n"
    printf "│ Welcome to DotFile Manager │                               │ e) Exit │\n"
    printf "╰────────────────────────────╯                               ╰─────────╯\n"
    printf "╭────────────────╮  ╭───────────────────────╮  ╭───────────────────────╮\n"
    printf "│ s) Search Tool │  │ f) Favourite DotFiles │  │ t) Tool Configuration │\n"
    printf "╰────────────────╯  ╰───────────────────────╯  ╰───────────────────────╯\n"
    printf "╭────────────────────╮  ╭────────────────────╮  ╭──────────────────────╮\n"
    printf "│ c) Config DotFiles │  │ u) Upload DotFiles │  │ d) Download DotFiles │\n"
    printf "╰────────────────────╯  ╰────────────────────╯  ╰──────────────────────╯\n"
    printf "\n➜ Select an option : "
    read option
    case $option in
        s) search_menu ;;
        f) favourite_dotfiles; main_menu ;;
        t) tool_configuration ;;
        c) select_file; edit_menu ;;
        u) select_file; upload_menu ;;
        d) download_menu ;;
        e) exit ;;
        *) main_menu ;;
    esac
    if [ $loop_mode -eq 1 ]; then
        menu
    fi
}

edit_menu () {
    clear
    printf "╭──────────────────╮\n"
    printf "│ Curently Editing │  ➤  \033[1m$file_path\033[0m\n"
    printf "╰──────────────────╯\n"
    printf "╭──────────────╮  ╭────────────────╮  ╭───────────────────╮  ╭───────────╮\n"
    printf "│ e) Edit File │  │ b) Backup File │  │ r) Restore Backup │  │ c) Cancel │\n"
    printf "╰──────────────╯  ╰────────────────╯  ╰───────────────────╯  ╰───────────╯\n"
    printf "\n➜ Select an option : "
    read option
    case $option in
        e) edit_file ;;
        b) backup_file ;;
        r) restore_file ;;
        c) main_menu ;;
        *) config_menu ;;
    esac
}

search_menu () {
    clear
    printf "╭─────────────╮\n"
    printf "│ Search Tool │\n"
    printf "╰─────────────╯\n"
    printf "\n➜ Search for a file : "
    read file_name
    list_files "/home/$USER/" $file_name 0
    list_files "/home/$USER/.config/" $file_name 0

    while [ -d $file_path ]; do
        clear
        printf "╭────────────────────────╮\n"
        printf "│ Corresponding Files In │  ➤  \033[1m$file_path\033[0m\n"
        printf "╰────────────────────────╯\n\n"
        if [ "$file_name" == "$(basename $file_path)" ]; then
            colorls -a --sd $file_path
        else
            list_files $file_path $file_name 1
        fi
        printf "\n➜ Select a file : "
        read file_name
        if [ -e $file_path/$file_name ]; then
            file_path=$file_path$file_name
            if [ -d $file_path ]; then
                file_path=$file_path/
            elif [ -f $file_path ]; then
                edit_menu
                break
            fi
        else
            search_menu
        fi
    done
}

list_files () {
    if [ -n "$(colorls -a --sd $1 | grep $2)" ]; then
        file_path=$1
        if [ $3 -eq 1 ]; then
            colorls -a --sd $1 | grep $2
        fi
    fi
}

clean_path () {
    if [ "${file_path##*/}" == "." ]; then
        file_path="${file_path%/*}"
    elif [ "${file_path##*/}" == ".." ]; then
        file_path="${file_path%/*}"
        file_path="${file_path%/*}"
    fi
}

select_file () {
    clear

    list_files "/home/$USER/"
    list_files "/home/$USER/.config/"

    printf "➜ Select a file / folder : "
    read file

    if [ -e "/home/$USER/$file" ]; then
        file_path="/home/$USER/$file"
    elif [ -e "/home/$USER/.config/$file" ]; then
        file_path="/home/$USER/.config/$file"
    else
        select_file
    fi

    while [ -d "$file_path" ]; do
        clear
        clean_path
        list_files "$file_path"
        printf "\n❯ Select a file / folder : "
        read file
        if [ -e "$file_path/$file" ]; then
            file_path="$file_path/$file"
            backup_path="$file_path.backup"
        fi
    done
}

edit_file () {
    if [ $edit_confirm -eq 1 ]; then
        $editor $flags $file_path
    elif [ $edit_confirm -eq 2 ]; then
        printf "\n➜ Edit [%s] [y/n] : " $file_path
        read edit
        case $edit in
            "y" | "yes" | "Y" | "Yes" | "YES") $editor $flags $file_path ;;
            "n" | "no" | "N" | "No" | "NO") config_menu;;
            *) edit_file ;;
        esac
    fi
}

backup_file () {
    if [ $backup_mode -eq 1 ]; then
        cp $file_path $backup_path
    elif [ $backup_mode -eq 2 ]; then
        printf "\n➜ Backup [%s] to [%s] [y/n] : " $file_path $backup_path
        read backup
        case $backup in
            "y" | "yes" | "Y" | "Yes" | "YES") cp $file_path $backup_path ;;
            "n" | "no" | "N" | "No" | "NO") ;;
            *) backup_file ;;
        esac
    fi
}

restore_backup () {
    if [ $restore_confirm -eq 1 ]; then
        cp $backup_path $file_path
    elif [ $restore_confirm -eq 2 ]; then
        printf "\n➜ Restore [%s] from [%s] [y/n] : " $file_path $backup_path
        read restore
        case $restore in
            "y" | "yes" | "Y" | "Yes" | "YES") cp $backup_path $file_path ;;
            "n" | "no" | "N" | "No" | "NO") ;;
            *) restore_backup ;;
        esac
    fi
}

main_menu
clear